### ISSUE TITLE
Button and Fields have diffrent Styles

### ISSUE THREAD

**Issue by MaxHarrisonGit** [langleyfoxall/react-dynamic-form-builder#23]
Could we have the Button and Fields have a diffrent invalid style?

**Comment by NilesB** [comment]
You can achieve this with CSS.

On a CSS style you can specify the element type and the class. [Here's an example of this](https://codepen.io/nilesb/pen/jJEqON).

As you can see the `invalid` class gives elements a red outline. On divs however it is overriden to be a blue outline.
