### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Jord-JD** [langleyfoxall/react-dynamic-form-builder#3]
Currently the project has no documentation. This issue is here to track / discuss the require installation and usage documentation.

**Comment by dextermb** [comment]
Documentation would be great! There's so many little caveats that you can do with this package. I've even made an "addon" package which can be found at [`@ninetynine/react-dynamic-select`](https://github.com/ninetynine/react-dynamic-select). Would be nice to have a list of community addons/plugins too.

Edit: Renamed package to `@ninetynine/react-dynamic-form-select`. I've also created another package [`@ninetynine/react-dynamic-form-datepicker`](https://github.com/ninetynine/react-dynamic-form-datepicker).

**Comment by jaredkove** [comment]
@dextermb shameless plugging there. well done.

if ONLY you just added to the original package ;)

**Comment by dextermb** [comment]
> if ONLY you just added to the original package ;)

Hm? I wrote both of them, and I point to langley foxall's form builder on each one 🤔 💭

**Comment by Jord-JD** [comment]
Initial documentation is provided by PR #9.

**Comment by dextermb** [comment]
I've written some more detailed documentation in #17- check it out.
